#!/usr/bin/env python3
"""Render docs/infrastructure/topology.{md,html} from topology.yaml.

Usage (from repo root):
  python3 scripts/render-topology.py
"""

from __future__ import annotations

import html
from pathlib import Path

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise SystemExit(
        "PyYAML required: pip install pyyaml  (or: apt install python3-yaml)"
    ) from exc

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "docs" / "infrastructure" / "topology.yaml"
OUT_MD = ROOT / "docs" / "infrastructure" / "topology.md"
OUT_HTML = ROOT / "docs" / "infrastructure" / "topology.html"

GENERATED_BANNER = (
    "<!-- Generated by scripts/render-topology.py from topology.yaml — do not edit -->"
)


def esc(s: object) -> str:
    return html.escape(str(s), quote=True)


def status_badge(status: str) -> str:
    return f'<span class="badge badge-{esc(status)}">{esc(status)}</span>'


def load() -> dict:
    with SRC.open(encoding="utf-8") as f:
        return yaml.safe_load(f)


def ascii_tree(data: dict) -> str:
    lan = data["lan"]
    hosts = {h["id"]: h for h in data["hosts"]}
    pve = hosts["pve"]
    vm = hosts["maktaba-vm"]
    lines = [
        f"Internet → ISP router ({lan['gateway']})",
        f"              └─ LAN {lan['subnet']}",
        f"                    ├─ Proxmox pve ({pve['lan_ip']}, TS {pve['tailscale_ip']})",
        "                    │     └─ USB wdred 3.7T at /mnt/pve/wdred",
    ]
    layout = data["storage"][0]["layout"]
    for i, folder in enumerate(layout):
        flag = "" if folder.get("status") != "planned" else "  [planned]"
        branch = "└─" if i == len(layout) - 1 else "├─"
        if folder.get("exported"):
            lines.append(
                f"                    │           {branch} NFS {folder['path'].rstrip('/')} → maktaba VM{flag}"
            )
        else:
            lines.append(
                f"                    │           {branch} {folder['path'].rstrip('/')} (host-only){flag}"
            )
    lines.append(
        f"                    └─ Kubuntu maktaba VM ({vm['lan_ip']}, TS {vm['tailscale_ip']})"
    )
    live_svc = [s for s in data["services"] if s.get("status") == "live"]
    planned = [s for s in data["services"] if s.get("status") == "planned"]
    for i, s in enumerate(live_svc):
        branch = "└─" if i == len(live_svc) - 1 and not planned else "├─"
        lines.append(f"                          {branch} {s['name']}: {s['url']}")
    for i, s in enumerate(planned):
        branch = "└─" if i == len(planned) - 1 else "├─"
        lines.append(
            f"                          {branch} {s['name']} [planned]: {s['url']}"
        )
    return "\n".join(lines)


def mermaid(data: dict) -> str:
    """Compact flowchart for HTML (and optional MD)."""
    parts = [
        "flowchart TB",
        '  internet(["Internet"]) --> router["ISP router<br/>192.168.11.1"]',
        '  router --> lan["LAN 192.168.11.0/24"]',
        '  lan --> pve["Proxmox pve<br/>192.168.11.123 · TS 100.91.123.54"]',
        '  lan --> vm["Kubuntu maktaba VM<br/>192.168.11.141 · TS 100.68.38.53"]',
        '  pve --> wdred[("wdred USB ~3.7T<br/>/mnt/pve/wdred")]',
    ]
    for folder in data["storage"][0]["layout"]:
        fid = folder["path"].rstrip("/").replace("/", "_").replace(".", "_")
        label = folder["path"].rstrip("/")
        if folder.get("status") == "planned":
            label += " · planned"
        parts.append(f'  wdred --> {fid}["{label}"]')
        if folder.get("exported"):
            parts.append(f"  {fid} -->|NFS| vm")
    for s in data["services"]:
        sid = s["id"].replace("-", "_")
        label = s["name"]
        if s.get("status") == "planned":
            label += " · planned"
        parts.append(f'  vm --> {sid}["{label}<br/>{s["url"]}"]')
    return "\n".join(parts)


def render_md(data: dict) -> str:
    meta = data["meta"]
    lan = data["lan"]
    dns = data["dns"]
    remote = data["remote_access"]

    out: list[str] = []
    out.append(f"<!-- Generated by scripts/render-topology.py from topology.yaml — do not edit by hand -->")
    out.append(f"# {meta['title']}")
    out.append("")
    out.append(f"**Updated:** {meta['updated']}")
    out.append("")
    out.append(meta["description"].strip())
    out.append("")
    out.append(
        "**Source of truth:** [`topology.yaml`](./topology.yaml) · "
        "**Scan page:** [`topology.html`](./topology.html) · "
        "Regenerate: `python3 scripts/render-topology.py`"
    )
    out.append("")
    out.append("## Tree")
    out.append("")
    out.append("```")
    out.append(ascii_tree(data))
    out.append("```")
    out.append("")
    out.append("## Hosts")
    out.append("")
    out.append("| Host | Role | LAN | Tailscale | Status |")
    out.append("| --- | --- | --- | --- | --- |")
    for h in data["hosts"]:
        out.append(
            f"| {h['name']} | {h['role']} | `{h['lan_ip']}` | `{h['tailscale_ip']}` | {h['status']} |"
        )
    out.append("")
    out.append("## Services")
    out.append("")
    out.append("| Service | URL | Live path | Edge | Status | Notes |")
    out.append("| --- | --- | --- | --- | --- | --- |")
    for s in data["services"]:
        notes = " ".join(str(s.get("notes", "")).split())
        out.append(
            f"| {s['name']} | {s['url']} | `{s['live_path']}` | {s['edge']} | {s['status']} | {notes} |"
        )
    out.append("")
    out.append("## Storage (wdred)")
    out.append("")
    out.append("| Folder | Purpose | NFS export | Mount on guest | Clients | Status |")
    out.append("| --- | --- | --- | --- | --- | --- |")
    for folder in data["storage"][0]["layout"]:
        status = folder.get("status", "live")
        if folder.get("exported"):
            out.append(
                f"| `{folder['path']}` | {folder['purpose']} | "
                f"`{folder['nfs_export']}` → `{folder['mount_path']}` | "
                f"{folder['mount_on']} | {', '.join(folder.get('clients', []))} | {status} |"
            )
        else:
            out.append(
                f"| `{folder['path']}` | {folder['purpose']} | — (host-only) | — | — | {status} |"
            )
    out.append("")
    out.append("## Edge (Caddy)")
    out.append("")
    out.append("| Proxy | Binds | TLS | Sites |")
    out.append("| --- | --- | --- | --- |")
    for e in data["edges"]:
        sites = "; ".join(
            f"{site['host']} → {site['backend']}"
            + (f" [{site['status']}]" if site.get("status") and site["status"] != "live" else "")
            for site in e["sites"]
        )
        tls = e.get("tls", "—")
        out.append(f"| {e['name']} | `{e['binds']}` | {tls} | {sites} |")
    out.append("")
    out.append("## DNS")
    out.append("")
    out.append(f"- **Domain:** `{dns['domain']}`")
    out.append(f"- **Mode:** {dns['mode']}")
    out.append(f"- **Nameserver:** `{dns['nameserver']}`")
    for n in dns.get("notes", []):
        out.append(f"- {n}")
    out.append("")
    out.append("## Remote access")
    out.append("")
    out.append(f"- **Default:** {remote['default']}")
    out.append(
        "- **Not exposed to internet:** " + ", ".join(remote["not_exposed"])
    )
    out.append(f"- See also: [`{remote['see_also']}`](../vaultwarden/remote-access.md)")
    out.append("")
    out.append("## Invariants")
    out.append("")
    for inv in data["invariants"]:
        out.append(f"- {inv}")
    out.append("")
    out.append("## Related")
    out.append("")
    out.append("- [`network.md`](./network.md) — short pointer + links")
    out.append("- [`projects/REGISTRY.md`](../../projects/REGISTRY.md) — gate for live services")
    out.append("- [`docs/immich/setup-plan.md`](../immich/setup-plan.md) — Immich rollout")
    out.append("- [`docs/maktaba/usb-wdred-runbook.md`](../maktaba/usb-wdred-runbook.md) — USB/NFS ops")
    out.append("")
    # silence unused
    _ = lan
    return "\n".join(out)


def render_html(data: dict) -> str:
    meta = data["meta"]
    lan = data["lan"]
    dns = data["dns"]
    remote = data["remote_access"]
    mermaid_src = mermaid(data)

    host_cards = []
    for h in data["hosts"]:
        notes = "".join(f"<li>{esc(n)}</li>" for n in h.get("notes", []))
        host_cards.append(
            f"""
        <article class="card">
          <div class="card-head">
            <h3>{esc(h['name'])}</h3>
            {status_badge(h['status'])}
          </div>
          <p class="role">{esc(h['role'])}</p>
          <dl class="meta">
            <div><dt>LAN</dt><dd><code>{esc(h['lan_ip'])}</code></dd></div>
            <div><dt>Tailscale</dt><dd><code>{esc(h['tailscale_ip'])}</code></dd></div>
          </dl>
          <ul class="notes">{notes}</ul>
        </article>"""
        )

    svc_rows = []
    for s in data["services"]:
        notes = " ".join(str(s.get("notes", "")).split())
        svc_rows.append(
            f"""
          <tr class="status-{esc(s['status'])}">
            <td><strong>{esc(s['name'])}</strong></td>
            <td><a href="{esc(s['url'])}">{esc(s['url'])}</a></td>
            <td><code>{esc(s['live_path'])}</code></td>
            <td>{esc(s['edge'])}</td>
            <td>{status_badge(s['status'])}</td>
            <td>{esc(notes)}</td>
          </tr>"""
        )

    storage_rows = []
    for folder in data["storage"][0]["layout"]:
        status = folder.get("status", "live")
        if folder.get("exported"):
            nfs = f"<code>{esc(folder['nfs_export'])}</code> → <code>{esc(folder['mount_path'])}</code>"
            clients = esc(", ".join(folder.get("clients", [])))
        else:
            nfs = "— host-only"
            clients = "—"
        storage_rows.append(
            f"""
          <tr class="status-{esc(status)}">
            <td><code>{esc(folder['path'])}</code></td>
            <td>{esc(folder['purpose'])}</td>
            <td>{nfs}</td>
            <td>{clients}</td>
            <td>{status_badge(status)}</td>
          </tr>"""
        )

    edge_blocks = []
    for e in data["edges"]:
        sites = "".join(
            f"<li><code>{esc(site['host'])}</code> → <code>{esc(site['backend'])}</code> "
            f"{status_badge(site.get('status', 'live'))}</li>"
            for site in e["sites"]
        )
        edge_blocks.append(
            f"""
        <article class="card">
          <div class="card-head">
            <h3>{esc(e['name'])}</h3>
            {status_badge(e.get('status', 'live'))}
          </div>
          <dl class="meta">
            <div><dt>Binds</dt><dd><code>{esc(e['binds'])}</code></dd></div>
            <div><dt>TLS</dt><dd>{esc(e.get('tls', '—'))}</dd></div>
          </dl>
          <ul class="notes">{sites}</ul>
        </article>"""
        )

    invariants = "".join(f"<li>{esc(i)}</li>" for i in data["invariants"])
    dns_notes = "".join(f"<li>{esc(n)}</li>" for n in dns.get("notes", []))
    not_exposed = "".join(f"<li>{esc(n)}</li>" for n in remote["not_exposed"])

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{esc(meta['title'])}</title>
  {GENERATED_BANNER}
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <style>
    :root {{
      --bg: #0f1419;
      --surface: #1a2332;
      --surface2: #243044;
      --border: #2d3a4f;
      --text: #e6edf3;
      --muted: #8b9cb3;
      --accent: #58a6ff;
      --accent2: #3fb950;
      --warn: #d29922;
      --danger: #f85149;
      --purple: #bc8cff;
      --radius: 12px;
      --font: "Segoe UI", system-ui, -apple-system, sans-serif;
      --mono: "Cascadia Code", "Fira Code", "Consolas", monospace;
    }}
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: var(--font);
      background: var(--bg);
      color: var(--text);
      line-height: 1.6;
      min-height: 100vh;
    }}
    body::before {{
      content: "";
      position: fixed;
      inset: 0;
      background-image:
        linear-gradient(rgba(88,166,255,.03) 1px, transparent 1px),
        linear-gradient(90deg, rgba(88,166,255,.03) 1px, transparent 1px);
      background-size: 48px 48px;
      pointer-events: none;
      z-index: 0;
    }}
    .wrap {{
      position: relative;
      z-index: 1;
      max-width: 1100px;
      margin: 0 auto;
      padding: 2rem 1.5rem 4rem;
    }}
    header {{
      text-align: center;
      margin-bottom: 2.5rem;
      padding: 2.25rem 1.25rem;
      background: linear-gradient(135deg, var(--surface) 0%, #1e2a3a 100%);
      border: 1px solid var(--border);
      border-radius: var(--radius);
    }}
    header .eyebrow {{
      display: inline-block;
      font-size: .75rem;
      font-weight: 600;
      letter-spacing: .08em;
      text-transform: uppercase;
      color: var(--accent);
      background: rgba(88,166,255,.12);
      border: 1px solid rgba(88,166,255,.25);
      padding: .35rem .75rem;
      border-radius: 999px;
      margin-bottom: 1rem;
    }}
    h1 {{
      font-size: clamp(1.6rem, 4vw, 2.35rem);
      font-weight: 700;
      letter-spacing: -.02em;
      margin-bottom: .5rem;
    }}
    header p {{ color: var(--muted); max-width: 640px; margin: 0 auto; }}
    header .meta-line {{
      margin-top: 1rem;
      font-size: .9rem;
      color: var(--muted);
    }}
    header code {{
      font-family: var(--mono);
      font-size: .85em;
      background: var(--surface2);
      padding: .1rem .35rem;
      border-radius: 4px;
    }}
    section {{ margin-bottom: 2.25rem; }}
    h2 {{
      font-size: 1.25rem;
      font-weight: 600;
      margin-bottom: 1rem;
      display: flex;
      align-items: center;
      gap: .5rem;
    }}
    h2 .num {{
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 1.75rem;
      height: 1.75rem;
      font-size: .85rem;
      font-weight: 700;
      background: var(--accent);
      color: var(--bg);
      border-radius: 6px;
    }}
    .grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
      gap: 1rem;
    }}
    .card {{
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: var(--radius);
      padding: 1.15rem 1.35rem;
    }}
    .card-head {{
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: .75rem;
      margin-bottom: .35rem;
    }}
    .card h3 {{ font-size: 1.05rem; }}
    .role {{ color: var(--muted); font-size: .95rem; margin-bottom: .75rem; }}
    .meta {{
      display: grid;
      gap: .35rem;
      margin-bottom: .75rem;
    }}
    .meta div {{
      display: flex;
      gap: .5rem;
      font-size: .9rem;
    }}
    .meta dt {{ color: var(--muted); min-width: 5.5rem; }}
    .meta dd code, code {{
      font-family: var(--mono);
      font-size: .85em;
      background: var(--surface2);
      padding: .1rem .35rem;
      border-radius: 4px;
    }}
    .notes {{
      margin-left: 1.1rem;
      color: var(--muted);
      font-size: .9rem;
    }}
    .notes li {{ margin-bottom: .25rem; }}
    .badge {{
      display: inline-block;
      font-size: .7rem;
      font-weight: 700;
      letter-spacing: .04em;
      text-transform: uppercase;
      padding: .2rem .5rem;
      border-radius: 999px;
      border: 1px solid transparent;
      white-space: nowrap;
    }}
    .badge-live {{
      color: var(--accent2);
      background: rgba(63,185,80,.12);
      border-color: rgba(63,185,80,.35);
    }}
    .badge-planned {{
      color: var(--warn);
      background: rgba(210,153,34,.12);
      border-color: rgba(210,153,34,.35);
    }}
    .table-wrap {{
      overflow-x: auto;
      border: 1px solid var(--border);
      border-radius: var(--radius);
      background: var(--surface);
    }}
    table {{
      width: 100%;
      border-collapse: collapse;
      font-size: .9rem;
    }}
    th, td {{
      text-align: left;
      padding: .75rem 1rem;
      border-bottom: 1px solid var(--border);
      vertical-align: top;
    }}
    th {{
      color: var(--muted);
      font-weight: 600;
      font-size: .75rem;
      text-transform: uppercase;
      letter-spacing: .04em;
      background: var(--surface2);
    }}
    tr:last-child td {{ border-bottom: none; }}
    tr.status-planned td {{ opacity: .92; }}
    a {{ color: var(--accent); text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    .mermaid-wrap {{
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: var(--radius);
      padding: 1rem;
      overflow-x: auto;
    }}
    .mermaid {{ display: flex; justify-content: center; }}
    .callout {{
      background: linear-gradient(135deg, rgba(88,166,255,.08) 0%, var(--surface) 100%);
      border: 1px solid rgba(88,166,255,.35);
      border-radius: var(--radius);
      padding: 1rem 1.25rem;
      color: var(--muted);
      margin-bottom: 1rem;
    }}
    .callout strong {{ color: var(--text); }}
    .two-col {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
      gap: 1rem;
    }}
    footer {{
      margin-top: 2rem;
      padding-top: 1.25rem;
      border-top: 1px solid var(--border);
      color: var(--muted);
      font-size: .85rem;
      text-align: center;
    }}
    @media (max-width: 640px) {{
      th:nth-child(3), td:nth-child(3),
      th:nth-child(4), td:nth-child(4) {{ display: none; }}
    }}
  </style>
</head>
<body>
  <div class="wrap">
    <header>
      <div class="eyebrow">basehome-ops · infrastructure</div>
      <h1>{esc(meta['title'])}</h1>
      <p>{esc(meta['description'].strip())}</p>
      <p class="meta-line">
        Updated <strong>{esc(meta['updated'])}</strong> ·
        Source <code>topology.yaml</code> ·
        Agents: <a href="./topology.md">topology.md</a>
      </p>
    </header>

    <section>
      <div class="callout">
        <strong>Edit once.</strong> Change <code>docs/infrastructure/topology.yaml</code>,
        then run <code>python3 scripts/render-topology.py</code> to refresh this page and
        <code>topology.md</code>.
      </div>
    </section>

    <section>
      <h2><span class="num">1</span> Map</h2>
      <div class="mermaid-wrap">
        <pre class="mermaid">
{mermaid_src}
        </pre>
      </div>
    </section>

    <section>
      <h2><span class="num">2</span> Hosts</h2>
      <div class="grid">
        {"".join(host_cards)}
      </div>
      <p style="margin-top:1rem;color:var(--muted);font-size:.9rem">
        LAN <code>{esc(lan['subnet'])}</code> · gateway <code>{esc(lan['gateway'])}</code> ({esc(lan['gateway_label'])})
      </p>
    </section>

    <section>
      <h2><span class="num">3</span> Services</h2>
      <div class="table-wrap">
        <table>
          <thead>
            <tr>
              <th>Service</th>
              <th>URL</th>
              <th>Path</th>
              <th>Edge</th>
              <th>Status</th>
              <th>Notes</th>
            </tr>
          </thead>
          <tbody>
            {"".join(svc_rows)}
          </tbody>
        </table>
      </div>
    </section>

    <section>
      <h2><span class="num">4</span> Storage · wdred</h2>
      <div class="table-wrap">
        <table>
          <thead>
            <tr>
              <th>Folder</th>
              <th>Purpose</th>
              <th>NFS → mount</th>
              <th>Clients</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {"".join(storage_rows)}
          </tbody>
        </table>
      </div>
    </section>

    <section>
      <h2><span class="num">5</span> Edge · Caddy</h2>
      <div class="grid">
        {"".join(edge_blocks)}
      </div>
    </section>

    <section>
      <h2><span class="num">6</span> DNS &amp; access</h2>
      <div class="two-col">
        <article class="card">
          <div class="card-head"><h3>DNS</h3></div>
          <dl class="meta">
            <div><dt>Domain</dt><dd><code>{esc(dns['domain'])}</code></dd></div>
            <div><dt>Mode</dt><dd>{esc(dns['mode'])}</dd></div>
            <div><dt>NS</dt><dd><code>{esc(dns['nameserver'])}</code></dd></div>
          </dl>
          <ul class="notes">{dns_notes}</ul>
        </article>
        <article class="card">
          <div class="card-head"><h3>Remote access</h3></div>
          <p class="role">{esc(remote['default'])}</p>
          <p style="color:var(--muted);font-size:.9rem;margin-bottom:.5rem">Not exposed to internet:</p>
          <ul class="notes">{not_exposed}</ul>
        </article>
      </div>
    </section>

    <section>
      <h2><span class="num">7</span> Invariants</h2>
      <article class="card">
        <ul class="notes">{invariants}</ul>
      </article>
    </section>

    <footer>
      Related:
      <a href="./network.md">network.md</a> ·
      <a href="../immich/setup-plan.md">Immich setup plan</a> ·
      <a href="../../projects/REGISTRY.md">REGISTRY</a>
    </footer>
  </div>
  <script>
    mermaid.initialize({{
      startOnLoad: true,
      theme: "dark",
      flowchart: {{ curve: "basis", htmlLabels: true }},
      themeVariables: {{
        primaryColor: "#243044",
        primaryTextColor: "#e6edf3",
        primaryBorderColor: "#58a6ff",
        lineColor: "#8b9cb3",
        secondaryColor: "#1a2332",
        tertiaryColor: "#0f1419",
        fontFamily: "Segoe UI, system-ui, sans-serif"
      }}
    }});
  </script>
</body>
</html>
"""


def main() -> None:
    data = load()
    OUT_MD.write_text(render_md(data), encoding="utf-8")
    OUT_HTML.write_text(render_html(data), encoding="utf-8")
    print(f"Wrote {OUT_MD.relative_to(ROOT)}")
    print(f"Wrote {OUT_HTML.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
